<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8095a5e2-25fc-4ca2-a094-258c0c2a6452</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\LMS.EventBus\LMS.EventBus.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="9.5.4" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="9.5.4" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands/UpdateUserAvatar/" />
  </ItemGroup>

</Project>
