<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LMS.Upload.Application\LMS.Upload.Application.csproj" />
    <ProjectReference Include="..\LMS.Upload.Domain\LMS.Upload.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration/" />
    <Folder Include="Data/" />
    <Folder Include="Extensions/" />
    <Folder Include="Storage/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.15" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
